spring:
  application:
    name: backend
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-from: ${MAIL_FORM_EMAIL}
    properties:
      mail:
        smtp:
          from: rostislavsusak747@gmail.com
          auth: true
          starttls:
            enable: true
    protocol: smtp

  output:
    ansi:
      enabled: ALWAYS

jwt:
  secret:
    key: ${JWT_SECRET}

server:
  servlet:
    context-path: /api/v1